# Copyright 2022 Ben Woodward. All rights reserved.
# Use of this source code is governed by a GPL style
# license that can be found in the LICENSE file.
title = "len.to"
baseURL = "https://len.to/"
languageCode = "en-us"
paginate = 20
paginatePath = ""
[permalinks]
  img = "/img/:title/"
